### ISSUE TITLE
Explore github and overleaf integration

### ISSUE THREAD

**Issue by leingang** [leingang/gitpractice#6]
Find out if changes made in overleaf appear in github, or if it's a one-time deal.  And anything else about the setup.

Put it in a markdown (`.md`) file and submit a pull request.

**Comment by tiasondjaja** [comment]
I'm on it!

The short story: It looks like one way you could do this is through the local git repo.  You can specify two remote repos, one on github and one on Overleaf.  Will investigate more and write it up.
